version: '3.8'

services:
  backend:
    container_name: panameconsultingbackend
    build:
      context: .  # Contexte actuel (backend/)
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    
    image: panameconsulting:latest
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - HOSTNAME=0.0.0.0
      - TZ=Europe/Paris
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - MONGODB_URI=${MONGODB_URI}
      - FRONTEND_URL=https://panameconsulting.vercel.app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend-network
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs

volumes:
  uploads_data:
  logs_data:

networks:
  backend-network: